name: building, linting, testing
on: [push]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm i
      - name: build production project
        run: npm run build:prod
      - name: linting typeScript
        run: npm run lint
      - name: linting styles
        run: npm run lint:scss
      - name: unit tests
        run: npm run test:unit
